
classdef PoseAction < ros.Message
    %PoseAction MATLAB implementation of hector_uav_msgs/PoseAction
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'hector_uav_msgs/PoseAction' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '43e644b3792179ebbea93b0f3f1e801a' % The MD5 Checksum of the message definition
        PropertyList = { 'ActionGoal' 'ActionResult' 'ActionFeedback' } % List of non-constant message properties
        ROSPropertyList = { 'action_goal' 'action_result' 'action_feedback' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.hector_uav_msgs.PoseActionGoal' ...
            'ros.msggen.hector_uav_msgs.PoseActionResult' ...
            'ros.msggen.hector_uav_msgs.PoseActionFeedback' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        ActionGoal
        ActionResult
        ActionFeedback
    end
    methods
        function set.ActionGoal(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.hector_uav_msgs.PoseActionGoal'};
            validateattributes(val, validClasses, validAttributes, 'PoseAction', 'ActionGoal')
            obj.ActionGoal = val;
        end
        function set.ActionResult(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.hector_uav_msgs.PoseActionResult'};
            validateattributes(val, validClasses, validAttributes, 'PoseAction', 'ActionResult')
            obj.ActionResult = val;
        end
        function set.ActionFeedback(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.hector_uav_msgs.PoseActionFeedback'};
            validateattributes(val, validClasses, validAttributes, 'PoseAction', 'ActionFeedback')
            obj.ActionFeedback = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.hector_uav_msgs.PoseAction.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.hector_uav_msgs.PoseAction(strObj);
        end
    end
end
