
classdef TakeoffAction < ros.Message
    %TakeoffAction MATLAB implementation of hector_uav_msgs/TakeoffAction
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'hector_uav_msgs/TakeoffAction' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'a3b6083cae7da419ac7a4cb028a39fb6' % The MD5 Checksum of the message definition
        PropertyList = { 'ActionGoal' 'ActionResult' 'ActionFeedback' } % List of non-constant message properties
        ROSPropertyList = { 'action_goal' 'action_result' 'action_feedback' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.hector_uav_msgs.TakeoffActionGoal' ...
            'ros.msggen.hector_uav_msgs.TakeoffActionResult' ...
            'ros.msggen.hector_uav_msgs.TakeoffActionFeedback' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        ActionGoal
        ActionResult
        ActionFeedback
    end
    methods
        function set.ActionGoal(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.hector_uav_msgs.TakeoffActionGoal'};
            validateattributes(val, validClasses, validAttributes, 'TakeoffAction', 'ActionGoal')
            obj.ActionGoal = val;
        end
        function set.ActionResult(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.hector_uav_msgs.TakeoffActionResult'};
            validateattributes(val, validClasses, validAttributes, 'TakeoffAction', 'ActionResult')
            obj.ActionResult = val;
        end
        function set.ActionFeedback(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.hector_uav_msgs.TakeoffActionFeedback'};
            validateattributes(val, validClasses, validAttributes, 'TakeoffAction', 'ActionFeedback')
            obj.ActionFeedback = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.hector_uav_msgs.TakeoffAction.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.hector_uav_msgs.TakeoffAction(strObj);
        end
    end
end
