
classdef TakeoffFeedback < ros.Message
    %TakeoffFeedback MATLAB implementation of hector_uav_msgs/TakeoffFeedback
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'hector_uav_msgs/TakeoffFeedback' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'dd7058fae6e1bf2400513fe092a44c92' % The MD5 Checksum of the message definition
        PropertyList = { 'CurrentPose' } % List of non-constant message properties
        ROSPropertyList = { 'current_pose' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.geometry_msgs.PoseStamped' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        CurrentPose
    end
    methods
        function set.CurrentPose(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.PoseStamped'};
            validateattributes(val, validClasses, validAttributes, 'TakeoffFeedback', 'CurrentPose')
            obj.CurrentPose = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.hector_uav_msgs.TakeoffFeedback.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.hector_uav_msgs.TakeoffFeedback(strObj);
        end
    end
end
